FROM owlbarn/owl:latest
USER root

# prepare dependency

RUN echo 'export PATH=/home/opam/.cabal/bin:${PATH}' >> /home/opam/.bashrc
RUN apt-get update && apt-get install -y cabal-install
RUN cabal update && cabal install pandoc pandoc-citeproc pandoc-crossref

# install full latex package

RUN apt-get install -y texlive-full

ENTRYPOINT /bin/bash